input {
  tcp { port => 5044 codec => json_lines }
}
filter {
  mutate { add_field => { "course" => "network-devops" } }
}
output {
  elasticsearch { hosts => ["http://elasticsearch:9200"] index => "network-devops-%{+YYYY.MM.dd}" }
  stdout { codec => rubydebug }
}
